name: Mirror Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }},workspace

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Create PR in Private Monorepo
        uses: peter-evans/create-pull-request@v6
        with:
          # A PAT with repo scope for a bot user that has write access to the private repo
          token: ${{ steps.generate_token.outputs.token }}
          # The private monorepo where the new PR will be created
          repository: ruforms/workspace
          # The branch in the private monorepo to base the new PR on
          base: main
          # The name for the new branch in the private monorepo
          branch: contrib/${{ github.repository_owner }}-${{ github.event.pull_request.number }}
          # The title for the new PR in the private monorepo
          title: "Contrib: Mirror PR from ${{ github.repository }}#${{ github.event.pull_request.number }}"
          # The body of the new PR
          body: |
            ## Mirrored Pull Request

            **Original PR:** [${{ github.repository }}#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})
            **Author:** @${{ github.event.pull_request.user.login }}

            ---

            ${{ github.event.pull_request.body }}

          # The path within the private monorepo where the files should be placed
          path: libs/${{ github.event.repository.name }}

      - name: Post Comment on Original PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          # A PAT with repo scope for the bot user
          token: ${{ steps.generate_token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            👋 Thank you for your contribution, @${{ github.event.pull_request.user.login }}!

            I am a bot, and I have mirrored your pull request to our private development repository for review. All tests and discussion will happen there. You can view the mirrored PR at the link that will appear below this comment shortly.

            I will keep this PR updated with the status from the private repository.
